name: Crystal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v1
    - name: Install libsoundio
      run: |
        apt update && apt install -y cmake
        git clone -b 2.0.0 https://github.com/andrewrk/libsoundio.git
        cd libsoundio
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make
        make install
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
        crystal spec
