name: Crystal CI

on:
  push:
  schedule:
      - cron: '0 0 * * *' 

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest, nightly]
        
    runs-on: ubuntu-latest

    steps:
    - name: Download source
      uses: actions/checkout@v2
    - name: Install Crystal
      uses: oprypin/install-crystal@v1
      with:
          crystal: ${{ matrix.crystal }}
    - name: Install libsoundio
      run: |
        sudo apt install -y cmake
        git clone -b 2.0.0 https://github.com/andrewrk/libsoundio.git
        cd libsoundio
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make
        make install
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
        crystal spec
