name: Crystal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - name: Install libsoundio
      run: apt update && apt install libsoundio-dev
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
